import {
  BedrockClient,
  ListFoundationModelsCommand,
} from "@aws-sdk/client-bedrock";

const client = new BedrockClient();

const template = `// This files has been autogenerated - do not modify

export class Models {
{placeholderText}
}

export class ImageModels {
{placeholderImage}
}`;

(async () => {
  const textModels = (
    await client.send(
      new ListFoundationModelsCommand({
        byInferenceType: "ON_DEMAND",
        byOutputModality: "TEXT",
      })
    )
  ).modelSummaries
    ?.filter((ms) => ms.modelLifecycle?.status == "ACTIVE")
    .map((ms) => ms.modelId);
  const imageModels = (
    await client.send(
      new ListFoundationModelsCommand({
        byInferenceType: "ON_DEMAND",
        byOutputModality: "IMAGE",
      })
    )
  ).modelSummaries
    ?.filter((ms) => ms.modelLifecycle?.status == "ACTIVE")
    .map((ms) => ms.modelId);
  const textModelStrings = textModels?.map(
    (m) =>
      `  public static readonly ${m?.replace(/\-/g, "_").replace(/\./g, "_").replace(/\:/g, "_").toUpperCase()} = "${m}";`
  );
  const imageModelStrings = imageModels?.map(
    (m) =>
      `  public static readonly ${m?.replace(/\-/g, "_").replace(/\./g, "_").replace(/\:/g, "_").toUpperCase()} = "${m}";`
  );
  let output = template;
  if (textModelStrings) {
    output = output.replace("{placeholderText}", textModelStrings.join("\n"));
  }
  if (imageModelStrings) {
    output = output.replace("{placeholderImage}", imageModelStrings.join("\n"));
  }
  console.log(output);
})();
