import {
  BedrockClient,
  ListFoundationModelsCommand,
} from "@aws-sdk/client-bedrock";

const clientWest = new BedrockClient({ region: "us-west-2" });
const clientEast = new BedrockClient({ region: "us-east-1" });

const template = `// This files has been autogenerated - do not modify

export class Models {
{placeholderText}
}

export class ImageModels {
{placeholderImage}
}`;

async function getModels(
  client: BedrockClient,
  modality: "TEXT" | "IMAGE"
): Promise<[string | undefined, string | undefined][]> {
  const resp = await client.send(
    new ListFoundationModelsCommand({
      byInferenceType: "ON_DEMAND",
      byOutputModality: modality,
    })
  );
  return (
    resp.modelSummaries?.map((ms) => [
      ms.modelId,
      ms.modelLifecycle?.status?.toString(),
    ]) ?? []
  );
}

(async () => {
  let output = template;
  try {
    const textModelsWest = await getModels(clientWest, "TEXT");

    const imageModelsWest = await getModels(clientWest, "IMAGE");

    const textModelsEast = await getModels(clientEast, "TEXT");

    const imageModelsEast = await getModels(clientEast, "IMAGE");
    //console.log("J", textModels, textModels);
    const textModels = [
      ...new Set([
        ...textModelsEast.map((m) => JSON.stringify(m)),
        ...textModelsWest.map((m) => JSON.stringify(m)),
      ]).values(),
    ].map((x) => JSON.parse(x));
    const imageModels = [
      ...new Set([
        ...imageModelsEast.map((m) => JSON.stringify(m)),
        ...imageModelsWest.map((m) => JSON.stringify(m)),
      ]).values(),
    ].map((x) => JSON.parse(x));

    const textModelStrings = textModels?.map(
      (m) =>
        `  ${m[1] !== "ACTIVE" ? "/** @deprecated this model has reached end-of-life */\n  " : ""}public static readonly ${m[0]?.replace(/\-/g, "_").replace(/\./g, "_").replace(/\:/g, "_").toUpperCase()} = "${m[0]}";`
    );
    const imageModelStrings = imageModels?.map(
      (m) =>
        `  ${m[1] !== "ACTIVE" ? "/** @deprecated this model has reached end-of-life */\n  " : ""}public static readonly ${m[0]?.replace(/\-/g, "_").replace(/\./g, "_").replace(/\:/g, "_").toUpperCase()} = "${m[0]}";`
    );
    if (textModelStrings) {
      output = output.replace("{placeholderText}", textModelStrings.join("\n"));
    }
    if (imageModelStrings) {
      output = output.replace(
        "{placeholderImage}",
        imageModelStrings.join("\n")
      );
    }
  } catch {}

  console.log(output);
})();
