// This files has been autogenerated - do not modify

export class Models {
  public static readonly ANTHROPIC_CLAUDE_SONNET_4_20250514_V1_0 =
    "anthropic.claude-sonnet-4-20250514-v1:0";
  public static readonly OPENAI_GPT_OSS_120B_1_0 = "openai.gpt-oss-120b-1:0";
  public static readonly TWELVELABS_PEGASUS_1_2_V1_0 =
    "twelvelabs.pegasus-1-2-v1:0";
  public static readonly ANTHROPIC_CLAUDE_SONNET_4_5_20250929_V1_0 =
    "anthropic.claude-sonnet-4-5-20250929-v1:0";
  public static readonly QWEN_QWEN3_CODER_30B_A3B_V1_0 =
    "qwen.qwen3-coder-30b-a3b-v1:0";
  public static readonly QWEN_QWEN3_32B_V1_0 = "qwen.qwen3-32b-v1:0";
  public static readonly OPENAI_GPT_OSS_20B_1_0 = "openai.gpt-oss-20b-1:0";
  public static readonly ANTHROPIC_CLAUDE_OPUS_4_1_20250805_V1_0 =
    "anthropic.claude-opus-4-1-20250805-v1:0";
  public static readonly AMAZON_TITAN_TG1_LARGE = "amazon.titan-tg1-large";
  public static readonly AMAZON_NOVA_PREMIER_V1_0 = "amazon.nova-premier-v1:0";
  public static readonly AMAZON_NOVA_PRO_V1_0 = "amazon.nova-pro-v1:0";
  public static readonly AMAZON_NOVA_LITE_V1_0 = "amazon.nova-lite-v1:0";
  public static readonly AMAZON_NOVA_MICRO_V1_0 = "amazon.nova-micro-v1:0";
  public static readonly AMAZON_NOVA_SONIC_V1_0 = "amazon.nova-sonic-v1:0";
  public static readonly AMAZON_TITAN_TEXT_LITE_V1 =
    "amazon.titan-text-lite-v1";
  public static readonly AMAZON_TITAN_TEXT_EXPRESS_V1 =
    "amazon.titan-text-express-v1";
  public static readonly AI21_JAMBA_1_5_LARGE_V1_0 =
    "ai21.jamba-1-5-large-v1:0";
  public static readonly AI21_JAMBA_1_5_MINI_V1_0 = "ai21.jamba-1-5-mini-v1:0";
  /** @deprecated this model has reached end-of-life */
  public static readonly ANTHROPIC_CLAUDE_3_SONNET_20240229_V1_0 =
    "anthropic.claude-3-sonnet-20240229-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_HAIKU_20240307_V1_0 =
    "anthropic.claude-3-haiku-20240307-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_OPUS_20240229_V1_0 =
    "anthropic.claude-3-opus-20240229-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_5_SONNET_20240620_V1_0 =
    "anthropic.claude-3-5-sonnet-20240620-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_5_SONNET_20241022_V2_0 =
    "anthropic.claude-3-5-sonnet-20241022-v2:0";
  public static readonly ANTHROPIC_CLAUDE_3_7_SONNET_20250219_V1_0 =
    "anthropic.claude-3-7-sonnet-20250219-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_5_HAIKU_20241022_V1_0 =
    "anthropic.claude-3-5-haiku-20241022-v1:0";
  public static readonly ANTHROPIC_CLAUDE_OPUS_4_20250514_V1_0 =
    "anthropic.claude-opus-4-20250514-v1:0";
  public static readonly COHERE_COMMAND_R_V1_0 = "cohere.command-r-v1:0";
  public static readonly COHERE_COMMAND_R_PLUS_V1_0 =
    "cohere.command-r-plus-v1:0";
  public static readonly COHERE_RERANK_V3_5_0 = "cohere.rerank-v3-5:0";
  public static readonly DEEPSEEK_R1_V1_0 = "deepseek.r1-v1:0";
  public static readonly META_LLAMA3_8B_INSTRUCT_V1_0 =
    "meta.llama3-8b-instruct-v1:0";
  public static readonly META_LLAMA3_70B_INSTRUCT_V1_0 =
    "meta.llama3-70b-instruct-v1:0";
  public static readonly META_LLAMA3_1_8B_INSTRUCT_V1_0 =
    "meta.llama3-1-8b-instruct-v1:0";
  public static readonly META_LLAMA3_1_70B_INSTRUCT_V1_0 =
    "meta.llama3-1-70b-instruct-v1:0";
  public static readonly META_LLAMA3_2_11B_INSTRUCT_V1_0 =
    "meta.llama3-2-11b-instruct-v1:0";
  public static readonly META_LLAMA3_2_90B_INSTRUCT_V1_0 =
    "meta.llama3-2-90b-instruct-v1:0";
  public static readonly META_LLAMA3_2_1B_INSTRUCT_V1_0 =
    "meta.llama3-2-1b-instruct-v1:0";
  public static readonly META_LLAMA3_2_3B_INSTRUCT_V1_0 =
    "meta.llama3-2-3b-instruct-v1:0";
  public static readonly META_LLAMA3_3_70B_INSTRUCT_V1_0 =
    "meta.llama3-3-70b-instruct-v1:0";
  public static readonly META_LLAMA4_SCOUT_17B_INSTRUCT_V1_0 =
    "meta.llama4-scout-17b-instruct-v1:0";
  public static readonly META_LLAMA4_MAVERICK_17B_INSTRUCT_V1_0 =
    "meta.llama4-maverick-17b-instruct-v1:0";
  public static readonly MISTRAL_MISTRAL_7B_INSTRUCT_V0_2 =
    "mistral.mistral-7b-instruct-v0:2";
  public static readonly MISTRAL_MIXTRAL_8X7B_INSTRUCT_V0_1 =
    "mistral.mixtral-8x7b-instruct-v0:1";
  public static readonly MISTRAL_MISTRAL_LARGE_2402_V1_0 =
    "mistral.mistral-large-2402-v1:0";
  public static readonly MISTRAL_MISTRAL_SMALL_2402_V1_0 =
    "mistral.mistral-small-2402-v1:0";
  public static readonly MISTRAL_PIXTRAL_LARGE_2502_V1_0 =
    "mistral.pixtral-large-2502-v1:0";
  public static readonly QWEN_QWEN3_CODER_480B_A35B_V1_0 =
    "qwen.qwen3-coder-480b-a35b-v1:0";
  public static readonly QWEN_QWEN3_235B_A22B_2507_V1_0 =
    "qwen.qwen3-235b-a22b-2507-v1:0";
  public static readonly DEEPSEEK_V3_V1_0 = "deepseek.v3-v1:0";
  public static readonly AMAZON_RERANK_V1_0 = "amazon.rerank-v1:0";
  public static readonly META_LLAMA3_1_405B_INSTRUCT_V1_0 =
    "meta.llama3-1-405b-instruct-v1:0";
  public static readonly MISTRAL_MISTRAL_LARGE_2407_V1_0 =
    "mistral.mistral-large-2407-v1:0";
  public static readonly WRITER_PALMYRA_X4_V1_0 = "writer.palmyra-x4-v1:0";
  public static readonly WRITER_PALMYRA_X5_V1_0 = "writer.palmyra-x5-v1:0";
}

export class ImageModels {
  public static readonly STABILITY_STABLE_IMAGE_REMOVE_BACKGROUND_V1_0 =
    "stability.stable-image-remove-background-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_STYLE_GUIDE_V1_0 =
    "stability.stable-image-style-guide-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_CONTROL_SKETCH_V1_0 =
    "stability.stable-image-control-sketch-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_ERASE_OBJECT_V1_0 =
    "stability.stable-image-erase-object-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_CONTROL_STRUCTURE_V1_0 =
    "stability.stable-image-control-structure-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_SEARCH_RECOLOR_V1_0 =
    "stability.stable-image-search-recolor-v1:0";
  public static readonly STABILITY_STABLE_STYLE_TRANSFER_V1_0 =
    "stability.stable-style-transfer-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_SEARCH_REPLACE_V1_0 =
    "stability.stable-image-search-replace-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_INPAINT_V1_0 =
    "stability.stable-image-inpaint-v1:0";
  public static readonly AMAZON_TITAN_IMAGE_GENERATOR_V1 =
    "amazon.titan-image-generator-v1";
  public static readonly AMAZON_TITAN_IMAGE_GENERATOR_V2_0 =
    "amazon.titan-image-generator-v2:0";
  public static readonly AMAZON_NOVA_CANVAS_V1_0 = "amazon.nova-canvas-v1:0";
  /** @deprecated this model has reached end-of-life */
  public static readonly STABILITY_STABLE_DIFFUSION_XL_V1 =
    "stability.stable-diffusion-xl-v1";
  public static readonly STABILITY_SD3_5_LARGE_V1_0 =
    "stability.sd3-5-large-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_CORE_V1_1 =
    "stability.stable-image-core-v1:1";
  public static readonly STABILITY_STABLE_IMAGE_ULTRA_V1_1 =
    "stability.stable-image-ultra-v1:1";
}

export class VideoModels {
  public static readonly AMAZON_NOVA_REEL_V1_0 = "amazon.nova-reel-v1:0";
  public static readonly AMAZON_NOVA_REEL_V1_1 = "amazon.nova-reel-v1:1";
  public static readonly LUMA_RAY_V2_0 = "luma.ray-v2:0";
}
