// This files has been autogenerated - do not modify

export class Models {
  public static readonly AMAZON_TITAN_TG1_LARGE = "amazon.titan-tg1-large";
  public static readonly AMAZON_TITAN_TEXT_LITE_V1 =
    "amazon.titan-text-lite-v1";
  public static readonly AMAZON_TITAN_TEXT_EXPRESS_V1 =
    "amazon.titan-text-express-v1";
  public static readonly AI21_J2_GRANDE_INSTRUCT = "ai21.j2-grande-instruct";
  public static readonly AI21_J2_JUMBO_INSTRUCT = "ai21.j2-jumbo-instruct";
  public static readonly ANTHROPIC_CLAUDE_INSTANT_V1 =
    "anthropic.claude-instant-v1";
  public static readonly ANTHROPIC_CLAUDE_V2_1 = "anthropic.claude-v2:1";
  public static readonly ANTHROPIC_CLAUDE_V2 = "anthropic.claude-v2";
  public static readonly ANTHROPIC_CLAUDE_3_SONNET_20240229_V1_0 =
    "anthropic.claude-3-sonnet-20240229-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_HAIKU_20240307_V1_0 =
    "anthropic.claude-3-haiku-20240307-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_OPUS_20240229_V1_0 =
    "anthropic.claude-3-opus-20240229-v1:0";
  public static readonly ANTHROPIC_CLAUDE_3_5_SONNET_20240620_V1_0 =
    "anthropic.claude-3-5-sonnet-20240620-v1:0";
  public static readonly COHERE_COMMAND_TEXT_V14 = "cohere.command-text-v14";
  public static readonly COHERE_COMMAND_R_V1_0 = "cohere.command-r-v1:0";
  public static readonly COHERE_COMMAND_R_PLUS_V1_0 =
    "cohere.command-r-plus-v1:0";
  public static readonly COHERE_COMMAND_LIGHT_TEXT_V14 =
    "cohere.command-light-text-v14";
  public static readonly META_LLAMA3_8B_INSTRUCT_V1_0 =
    "meta.llama3-8b-instruct-v1:0";
  public static readonly META_LLAMA3_70B_INSTRUCT_V1_0 =
    "meta.llama3-70b-instruct-v1:0";
  public static readonly META_LLAMA3_1_8B_INSTRUCT_V1_0 =
    "meta.llama3-1-8b-instruct-v1:0";
  public static readonly META_LLAMA3_1_70B_INSTRUCT_V1_0 =
    "meta.llama3-1-70b-instruct-v1:0";
  public static readonly META_LLAMA3_1_405B_INSTRUCT_V1_0 =
    "meta.llama3-1-405b-instruct-v1:0";
  public static readonly MISTRAL_MISTRAL_7B_INSTRUCT_V0_2 =
    "mistral.mistral-7b-instruct-v0:2";
  public static readonly MISTRAL_MIXTRAL_8X7B_INSTRUCT_V0_1 =
    "mistral.mixtral-8x7b-instruct-v0:1";
  public static readonly MISTRAL_MISTRAL_LARGE_2402_V1_0 =
    "mistral.mistral-large-2402-v1:0";
  public static readonly MISTRAL_MISTRAL_LARGE_2407_V1_0 =
    "mistral.mistral-large-2407-v1:0";
}

export class ImageModels {
  public static readonly AMAZON_TITAN_IMAGE_GENERATOR_V1 =
    "amazon.titan-image-generator-v1";
  public static readonly AMAZON_TITAN_IMAGE_GENERATOR_V2_0 =
    "amazon.titan-image-generator-v2:0";
  public static readonly STABILITY_STABLE_DIFFUSION_XL_V1 =
    "stability.stable-diffusion-xl-v1";
  public static readonly STABILITY_SD3_LARGE_V1_0 = "stability.sd3-large-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_CORE_V1_0 =
    "stability.stable-image-core-v1:0";
  public static readonly STABILITY_STABLE_IMAGE_ULTRA_V1_0 =
    "stability.stable-image-ultra-v1:0";
}
